# Generated by Django 2.2.6 on 2019-10-18 01:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('message', models.CharField(max_length=4096)),
                ('changed_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096), blank=True, size=None)),
                ('branches', models.ManyToManyField(to='branches.Branches')),
                ('developers', models.ManyToManyField(to='developers.Developers')),
            ],
        ),
        migrations.CreateModel(
            name='CommitUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.Commits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commits',
            name='users',
            field=models.ManyToManyField(related_name='commit_updates', through='commits.CommitUpdates', to=settings.AUTH_USER_MODEL),
        ),
    ]
