# Generated by Django 2.2.6 on 2019-10-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '__first__'),
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='developers',
            field=models.ManyToManyField(to='developers.Developers'),
        ),
        migrations.AddField(
            model_name='commits',
            name='message',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
