# Generated by Django 2.2.6 on 2019-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='github_id',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
