# Generated by Django 2.2.6 on 2019-10-17 22:37

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_auto_20191017_2237'),
        ('commits', '0002_auto_20191017_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='commits',
            name='branches',
            field=models.ManyToManyField(to='branches.Branches'),
        ),
        migrations.AddField(
            model_name='commits',
            name='changed_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commits',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 22, 37, 6, 301327)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
        migrations.AddField(
            model_name='commitupdates',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.Commits'),
        ),
        migrations.AddField(
            model_name='commitupdates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commits',
            name='users',
            field=models.ManyToManyField(related_name='commit_updates', through='commits.CommitUpdates', to=settings.AUTH_USER_MODEL),
        ),
    ]
