# Generated by Django 2.2.6 on 2019-12-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
        ('commits', '0002_commits_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='repository',
            field=models.ManyToManyField(to='repositories.Repositories'),
        ),
    ]
