# Generated by Django 2.2.6 on 2019-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_commits_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='message',
            field=models.CharField(max_length=8192),
        ),
    ]
