# Generated by Django 2.2.6 on 2019-11-28 21:14

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('pulse_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('branches', models.ManyToManyField(to='branches.Branches')),
            ],
        ),
        migrations.CreateModel(
            name='RepositorySubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repositories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repositories',
            name='users',
            field=models.ManyToManyField(related_name='repository_subscribes', through='repositories.RepositorySubscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
