# Generated by Django 2.2.6 on 2019-10-17 21:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='branches',
            field=models.ManyToManyField(to='branches.Branches'),
        ),
        migrations.AddField(
            model_name='repositories',
            name='pulse_states',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repositories',
            name='stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repositories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repositories',
            name='users',
            field=models.ManyToManyField(related_name='repository_subscribes', through='repositories.Subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
