# Generated by Django 2.2.6 on 2019-10-17 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0002_auto_20191017_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribes',
            new_name='RepositorySubscriptions',
        ),
    ]
