# Generated by Django 2.2.6 on 2019-10-17 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperSubscribtions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='developers',
            name='users',
            field=models.ManyToManyField(related_name='developer_subscribes', through='developers.DeveloperSubscribtions', to=settings.AUTH_USER_MODEL),
        ),
    ]
