# Generated by Django 2.2.6 on 2019-12-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='mail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
