# Generated by Django 2.2.6 on 2019-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_developers_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='fullname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
