# Generated by Django 2.2.6 on 2019-12-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developers_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='fullname',
            new_name='name',
        ),
    ]
