# Generated by Django 2.2.6 on 2019-12-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_auto_20191205_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='mail',
            new_name='email',
        ),
    ]
